# Generated by Django 4.2.1 on 2023-05-23 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='added_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
